#!/usr/bin/with-contenv bash
# ==============================================================================
# Community Hass.io Add-ons: Nginx Proxy Manager
# Runs the nginx proxy manager interface
# ==============================================================================
# shellcheck disable=SC1091
source /usr/lib/hassio-addons/base.sh

declare -a options

options+=(--abort_on_uncaught_exception)
options+=("--max_old_space_size=250")

export NODE_ENV=production

cd /opt/nginx-proxy-manager || hass.die "Could not change directory to app"
exec node "${options[@]}" /opt/nginx-proxy-manager/src/backend/index.js
