---
name: Nginx Proxy Manager
version: dev
slug: nginxproxymanager
description: Manage Nginx proxy hosts with a simple, powerful interface
url: https://github.com/hassio-addons/addon-nginx-proxy-manager
webui: http://[HOST]:[PORT:81]
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
services:
  - mysql:need
hassio_api: true
ports:
  80/tcp: 80
  81/tcp: 81
  443/tcp: 443
ports_description:
  80/tcp: HTTP Entrance port
  81/tcp: Proxy management web interface
  443/tcp: HTTPS/SSL Entrance port
map:
  - ssl:rw
  - backup:rw
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  reset_database: bool?
